drop table if exists achievement_list CASCADE 
create table achievement
(id integer generated by default as identity,
achievement_description varchar(255),
achievement_name varchar(255),
achievement_unlocked boolean,
achievement_value integer,
primary key (id))