DROP TABLE IF EXISTS `achievement` CASCADE;
create table achievement
(id integer generated by default as identity,
achievement_name varchar(255),
achievement_description varchar(255),
achievement_value integer,
achievement_unlocked boolean,
primary key (id));